In [2]:
!pip install torchtext

  Using cached torchtext-0.15.2-cp310-cp310-win_amd64.whl (1.9 MB)
  Using cached torchdata-0.6.1-cp310-cp310-win_amd64.whl (1.3 MB)


You should consider upgrading via the 'C:\Users\DELL\Programming\python\StockReview.IntroAI.20222\venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [1]:
import pprint
import numpy as np
import pandas as pd

from sklearn import preprocessing, metrics

import torch
from torch import Tensor
from torch.utils.data import DataLoader
from torch.optim import AdamW
import torchtext
import torchtext.transforms as T
import torchtext.functional as F
from torchtext.models import RobertaClassificationHead, XLMR_BASE_ENCODER

import pickle

c:\Users\DELL\Programming\python\StockReview.IntroAI.20222\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
train_df = pd.read_json('data/stock_train.json')
test_df = pd.read_json('data/stock_test.json')

In [3]:
train_df

text     label  label_id
0     Tại thị trường trong nước, khảo sát lúc 9 giờ ...  positive         0
1     tăng 50.000 đồng/lượng ở cả hai chiều mua và b...  positive         0
2     Tại 2 thị trường lớn khác là Hà Nội và Đà Nẵng...  positive         0
3         Vàng lại bật tăng vượt ngưỡng 2.000 USD/ounce  positive         0
4            tăng 24 USD/ounce so với cùng giờ sáng qua  positive         0
...                                                 ...       ...       ...
1511  Danh mục đầu tư 60/40 là mô hình phân chia tài...   neutral         2
1512  Theo tính toán của Vanguard, lợi nhuận hàng nă...   neutral         2
1513  Nhóm chuyên gia JP Morgan xem xét 200 loại tài...   neutral         2
1514  Kết luận đưa ra là các nguyên tắc cốt lõi của ...   neutral         2
1515  Danh mục đầu tư 60/40, như tên gọi của nó, yêu...   neutral         2

[1516 rows x 3 columns]

In [4]:
test_df

text     label  label_id
0     Tại 2 thị trường lớn khác là Hà Nội và Đà Nẵng...  positive         0
1     Như vậy, trong 2 ngày qua, giá vàng nhẫn đã tă...  positive         0
2     Giá vàng thế giới bật tăng trở lại, khi lực cầ...  positive         0
3     Tại thị trường thế giới, thời điểm lúc 9 giờ 3...  positive         0
4     Tuy nhiên, sau đó lực cầu bắt đáy mạnh đã giúp...  positive         0
...                                                 ...       ...       ...
997   Ngoài 47 triệu cổ phiếu khớp lệnh, HAG còn ghi...   neutral         2
998                 báo cáo giải trình của SHS cho biết   neutral         2
999   Cuối quý I, SHS nắm giữ 2.240 tỷ đồng cổ phiếu...   neutral         2
1000  SHS còn nắm giữ hơn 420 tỷ đồng TCB với giá tr...   neutral         2
1001              Chứng khoán BOS thay dàn lãnh đạo mới   neutral         2

[1002 rows x 3 columns]

In [5]:
label_encoder = preprocessing.LabelEncoder()
train_df['label'] = label_encoder.fit_transform(train_df['label'])

In [6]:
test_df['label'] = label_encoder.transform(test_df['label'])

In [7]:
class PadTransform(torch.nn.Module):
    """Pad tensor to a fixed length with given padding value.

    :param max_length: Maximum length to pad to
    :type max_length: int
    :param pad_value: Value to pad the tensor with
    :type pad_value: bool
    """

    def __init__(self, max_length: int, pad_value: int) -> None:
        super().__init__()
        self.max_length = max_length
        self.pad_value = float(pad_value)
        
    def forward(self, x: Tensor) -> Tensor:
        """
        :param x: The tensor to pad
        :type x: Tensor
        :return: Tensor padded up to max_length with pad_value
        :rtype: Tensor
        """
        max_encoded_length = x.size(-1)
        if max_encoded_length < self.max_length:
            pad_amount = self.max_length - max_encoded_length
            x = torch.nn.functional.pad(x, (0, pad_amount), value=self.pad_value)
        return x

In [8]:
padding_idx = 1
bos_idx = 0
eos_idx = 2
max_seq_len = 256

In [9]:
text_transform = torchtext.models.XLMR_LARGE_ENCODER.transform()

In [10]:
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, df):
        self.df = df
    
    def __len__(self):
        return len(self.df)
    
    def __getitem__(self, idx):
        return (
            torch.tensor(text_transform(self.df.iloc[idx, 0])),
            torch.tensor(self.df.iloc[idx, 1])
        )

In [11]:
train_dataset = CustomDataset(train_df)
test_dataset = CustomDataset(test_df)

In [12]:
SMALL_BATCH_SIZE = 16
K = 2
LARGE_BATCH_SIZE = K * SMALL_BATCH_SIZE

In [13]:
def batch_collate_fn(batch):
    inp_list = list()
    tar_list = list()
    
    for sample in batch:
        inp_list.append(sample[0].tolist())
        tar_list.append(sample[1])
        
    padded_tensor = F.to_tensor(inp_list, padding_value=padding_idx)
    target_tensor = torch.stack(tar_list).type(torch.LongTensor)
    
    return padded_tensor, target_tensor

In [14]:
train_dataloader = DataLoader(
    dataset=train_dataset,
    batch_size=SMALL_BATCH_SIZE,
    shuffle=True,
    collate_fn=batch_collate_fn
)

In [15]:
test_dataloader = DataLoader(
    dataset=test_dataset,
    batch_size=SMALL_BATCH_SIZE,
    shuffle=False,
    collate_fn=batch_collate_fn
)

In [16]:
num_classes = 3
input_dim = 768

In [17]:
classifier_head = RobertaClassificationHead(num_classes=num_classes, input_dim=input_dim)
model = XLMR_BASE_ENCODER.get_model(head=classifier_head)

In [18]:
DEVICE = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

In [19]:
model.to(DEVICE)
pass  

In [20]:
learning_rate = 1.2e-5 
optim = AdamW(model.parameters(), lr=learning_rate)
criteria = torch.nn.CrossEntropyLoss()

In [22]:
def train_step(input, target, small_batch_no):
    output = model(input)
    loss = criteria(output, target)
    loss.backward()
    
    if (small_batch_no + 1) % K == 0 or (small_batch_no + 1) == len(train_dataloader):
        optim.step()
        optim.zero_grad()
    
    return loss.item() / input.size(dim=0)

def evaluate():
    model.eval()
    
    total_loss = 0
    counter = 0
    
    with torch.no_grad():
        for i, batch in enumerate(test_dataloader):
            input = batch[0].clone().detach().to(DEVICE)
            output = model(input)
            target = batch[1].clone().detach().to(DEVICE)
            
            if i == 0:
                class_output = torch.argmax(output, dim=1)
                class_target = target
            else:
                class_output = torch.cat([class_output, torch.argmax(output, dim=1)])
                class_target = torch.cat([class_target, target])
            
            loss = criteria(output, target).item()
            total_loss += loss
            
            counter += input.size(dim=0)
            
            
        confusion_matrix = metrics.confusion_matrix(
            class_target.cpu().numpy().flatten(),
            class_output.cpu().numpy().flatten(),
            labels=[0, 1, 2]
        ) 
        classification_report = metrics.classification_report(
            class_target.cpu().numpy().flatten(),
            class_output.cpu().numpy().flatten(),
            labels=[0, 1, 2],
            output_dict=True
        )

    return (
        total_loss,
        counter,
        confusion_matrix,
        classification_report
    )

In [27]:
num_epochs = 20

In [28]:
def save_log(epoch, **kwargs):
    with open(f'log_{epoch}.pkl', 'wb') as f:
        pickle.dump(kwargs, f)

def save_model(message):
    torch.save(model.state_dict(), f'model_{message}.pth')
    print('Model saved successfully')

In [29]:
max_accuracy = float('-inf')
max_macro_f1 = float('-inf')
max_weighted_f1 = float('-inf')

In [30]:
for epoch in range(num_epochs):
    model.train()
    
    avg_training_losses = list()
    
    for small_batch_no, small_batch in enumerate(train_dataloader):
        input = small_batch[0].clone().detach().to(DEVICE)
        target = small_batch[1].clone().detach().to(DEVICE)
        avg_training_losses.append(
            train_step(input, target, small_batch_no)
        )
        
        torch.cuda.empty_cache()

    total_loss, counter, confusion_matrix, classification_report = evaluate()
    print(f'EPOCH {epoch}')
    print(f'Mean of avg_training_losses={np.mean(avg_training_losses)}')
    print(f'total_loss={total_loss}')
    print(f'counter={counter}')
    print(f'loss=total_loss/counter={total_loss/counter}')
    print(f'confusion_matrix=\n{confusion_matrix}')
    
    print('classification_report=')
    pprint.pprint(classification_report)
    
    save_log(
        epoch,
        avg_training_losses=avg_training_losses,
        total_loss=total_loss,
        counter=counter,
        loss=total_loss/counter,
        confusion_matrix=confusion_matrix,
        classification_report=classification_report
    )
    
    if classification_report['accuracy'] > max_accuracy:
        print(f'New max_accuracy')
        max_accuracy = classification_report['accuracy']
        max_accuracy_index = epoch
        save_model('max_accuracy')
        
    elif classification_report['macro avg']['f1-score'] > max_macro_f1:
        print(f'New max_macro_f1')
        max_macro_f1 = classification_report['macro avg']['f1-score']
        max_macro_f1_index = epoch
        save_model('max_macro_f1')
    
    elif classification_report['weighted avg']['f1-score'] > max_weighted_f1:
        print(f'New max_weighted_f1')
        max_weighted_f1 = classification_report['weighted avg']['f1-score']
        max_weighted_f1_index = epoch
        save_model('max_weighted_f1')
    
    elif epoch == num_epochs - 1:
        save_model(f'{epoch}_last')
    
    elif epoch % 40 == 0:
        save_model(f'{epoch}_checkpoint')
        
    else:
        continue
    

save_log(
    'post_train_info',
    max_accuracy=max_accuracy,
    max_accuracy_index=max_accuracy_index,
    max_macro_f1=max_macro_f1,
    max_macro_f1_index=max_macro_f1_index,
    max_weighted_f1=max_weighted_f1,
    max_weighted_f1_index=max_weighted_f1_index
)

EPOCH 0
Mean of avg_training_losses=0.06755183995292897
total_loss=65.88427668809891
counter=1002
loss=total_loss/counter=0.0657527711458073
confusion_matrix=
[[193   2 128]
 [ 63  12 246]
 [ 38   2 318]]
classification_report=
{'0': {'f1-score': 0.6256077795786061,
       'precision': 0.6564625850340136,
       'recall': 0.5975232198142415,
       'support': 323},
 '1': {'f1-score': 0.07121661721068248,
       'precision': 0.75,
       'recall': 0.037383177570093455,
       'support': 321},
 '2': {'f1-score': 0.6057142857142858,
       'precision': 0.4595375722543353,
       'recall': 0.888268156424581,
       'support': 358},
 'accuracy': 0.5219560878243513,
 'macro avg': {'f1-score': 0.43417956083452475,
               'precision': 0.6220000524294497,
               'recall': 0.5077248512696387,
               'support': 1002},
 'weighted avg': {'f1-score': 0.4408957696748834,
                  'precision': 0.6160697263802778,
                  'recall': 0.5219560878243513,
        

In [31]:
def prepare_model():
    num_classes = 3
    input_dim = 768

    classifier_head = RobertaClassificationHead(num_classes=num_classes, input_dim=input_dim)
    model = XLMR_BASE_ENCODER.get_model(head=classifier_head)
    
    DEMO_MODEL_PATH = 'model_max_weighted_f1.pth'
    model.load_state_dict(torch.load(DEMO_MODEL_PATH))
    model.to(DEVICE)
    
    print(f'Loaded model to [{DEVICE}] in [{DEMO_MODEL_PATH}]')
    
    return model

In [32]:
def prepare_text_transform():
    text_transform = torchtext.models.XLMR_LARGE_ENCODER.transform()
    return text_transform

In [33]:
def predict(sentence, model, text_transform, label_map):
    transformed_text = text_transform(sentence)
    out = model(torch.tensor([transformed_text]).to(DEVICE))
    return label_map[torch.argmax(out).item()]

In [86]:
label_map = {
    0: 'negative',
    1: 'neutral',
    2: 'postive'
}

In [87]:
model = prepare_model()
text_transform = prepare_text_transform()

Loaded model to [cpu] in [model_max_weighted_f1.pth]


In [90]:
sample_text = 'Nền kinh tế đang trên bờ vực diệt vong'
predict(sample_text, model, text_transform, label_map)

'negative'